### ISSUE TITLE
Given that folder organization is typically reflected in name spacing ... 

### ISSUE THREAD

**Issue by WilliamBerryiii** [Voxelgon/Voxelgon#14]
How should the namespacing work?

**Comment by drewcassidy** [comment]
The first two levels (Voxelgon.Assets) should be ignored, so [/Assets/Voxelgon/ShipEditor/Wall.cs](https://github.com/Voxelgon/Voxelgon/blob/Develop/Assets/Voxelgon/ShipEditor/Wall.cs) would be in the Voxelgon.ShipEditor namespace. I cant just move the root of the project to /Assets since the .csproj is generated by Unity.app itself.

**Comment by WilliamBerryiii** [comment]
That's fair ... I'd just offer this SO thread as alternate input: http://stackoverflow.com/a/4672/1276028

**Comment by drewcassidy** [comment]
If this were a standalone project I would totally follow that, but since Unity forces a certain organization I dont really want to follow it here. It just feels redundant to put Assets at the root of the namespace.

**Comment by WilliamBerryiii** [comment]
Cool ... closing and I'll add a note to a contributors file.
